spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accountdb?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456


#seata:
#  enabled: true
#  tx-service-group: my_test_tx_group